name: Clone Private Repository Workflow

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Fit-Iuri/github-actions-training
          ref: refs/heads/BancoZap
          token: ${{ secrets.API_TOKEN_GITHUB }}
          fetch-depth: 0